<Project>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MicrosoftNETTestSdkVersion>18.8.1</MicrosoftNETTestSdkVersion>
    <NUnitVersion>4.6.1</NUnitVersion>
    <NUnit3TestAdapterVersion>6.2.0</NUnit3TestAdapterVersion>
  </PropertyGroup>
</Project>
